services:
  - type: web
    name: bcp-enrollment-ai
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
